### ISSUE TITLE
on index.html a featured or recommended games area

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#15]
on index.html a featured or recommended games area something like moving images just to show the user some popular games.

**Comment by DavidRod1865** [comment]
Hello! I would like to work on this issue. 

Are you looking for something like a carousel section?

**Comment by maddox05** [comment]
you can take creative freedom but something like that yeah. and yes it would be replacing it.

**Comment by DavidRod1865** [comment]
Okay - no problem! I'll start working on it tonight. Thanks!

**Comment by maddox05** [comment]
no problem! thanks for the help!

**Comment by maddox05** [comment]
someone can still take this issue.

**Comment by LightAndy1** [comment]
After the UI change, is this still needed? :)

**Comment by maddox05** [comment]
probably should make the main page look a bit better still but no this is not needed thanks @LightAndy1
