### ISSUE TITLE
readme needs to be updated, to look better and explain the project

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#18]
The current readme is lackluster and is not very helpful. Take creative freedom to make it look nice but also explain things like how to clone the project ( like a normal readme )

**Comment by DanielZhang111** [comment]
Can I get assigned and more information on what you want?

**Comment by Ajiboso-Adeola** [comment]
Hi @maddox05 , I would like to work on this issue

**Comment by maddox05** [comment]
you can both do it I'll just choose whichever is better. Just make a normal readme.md. kind of like this https://github.com/maddox05/Auto-Clicker where it shows u how to install it and cool features etc

**Comment by DanielZhang111** [comment]
So only one of us gets the pull/merge request??

**Comment by maddox05** [comment]
whoever gets it first, or whichever is better, just depends.

**Comment by DanielZhang111** [comment]
:O 
Ok then

**Comment by DanielZhang111** [comment]
I finished! Please check!

**Comment by DanielZhang111** [comment]
If there is anything missing, I will fix it (Assuming I know how to 😅 )

**Comment by maddox05** [comment]
done with pull req #19

**Comment by DanielZhang111** [comment]
Did this count for hacktoberfest?

**Comment by maddox05** [comment]
yes!

**Comment by DanielZhang111** [comment]
Thanks! I got it on the "waiting" list!
