### ISSUE TITLE
iframe created over mouse does not focus

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#23]
iframe focuses on mouse over and does not focus if the user has the mouse already over where the iframe is when its loaded. I have an idea to fix it, to when the window.location.includes /games/(currentgaeme.html) it can find the iframe and auto focus it.

**Comment by Virtual4087** [comment]
can i work on this issue?

**Comment by Virtual4087** [comment]
can you be a little more precise?

**Comment by Virtual4087** [comment]
When the user has a mouse over iframe before it loads, "iframe focused" doesn't get printed on console. Is that the only problem?
