### ISSUE TITLE
about.html on mobile

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#25]
about.html looks awful on mobile, can someone optimise it for mobile?

**Comment by Shubhangam333** [comment]
Assign this to me , I will optimise it

**Comment by maddox05** [comment]
assigned.

**Comment by Shubhangam333** [comment]
#26 Raised the PR for this fix. Please check . Thanks for providing me this opportunity

**Comment by maddox05** [comment]
close with pull req #26
