### ISSUE TITLE
more tab not hoverable on mobile

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#28]
hoverable is how mobile is opened but its not a thing on mobile. Have it so you can click to open and close more as well as keep the already implemented hover for it.

**Comment by LightAndy1** [comment]
Even though the solution may be simple, I did not find it. For the time being, until the problem gets fixed, I've made the MORE button always be expanded so that people can access the other pages on the mobile version.

> This is related to PR #47.
