### ISSUE TITLE
leaderboard.html is boring and can be better.

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#29]
page is implemented but looks bad. css needs to be updated.

**Comment by maddox05** [comment]
yes, although this problem will be a hard one and I would like to work closely with you to solve it. Please join the duckmath discord and message me there.

**Comment by Deepakktripathy** [comment]
sure thing!

**Comment by LightAndy1** [comment]
Hello, @maddox05. Could you kindly put me in charge of this issue? This would be relatively simple for me to fix :)

**Comment by maddox05** [comment]
Yes, I'm traveling rn when I get to my destination I'll assign you to the issue. I need to make a production branch but I'll just use main cuz why not.

**Comment by maddox05** [comment]
@LightAndy1 assigned srry for the wait
