### ISSUE TITLE
Tab titles - Question

### ISSUE THREAD

**Issue by LightAndy1** [duckmath/duckmath.github.io#34]
Hey there 👋,

I hope this message finds you well. I've been exploring the project on GitHub, and I have a few questions about the tab titles and overall design choices.

1. GAMES Tab: I noticed that it's labelled as "G4M3S." Could you provide some insights into why it's not simply "GAMES"?

2. Unbl0ck3rs Tab: Similarly, I'm curious about the use of "Unbl0ck3rs" instead of "Unblockers." What's the reasoning behind this specific styling? Also, could you shed some light on what the "Unbl0ck3rs" tab is supposed to mean or do?

3. Discord Tab: The Discord tab is named "D1sc0rd." Is there a specific reason for this unique naming convention?

4. Game Request Tab: Lastly, the "Game Request" tab is labelled as "G4m3 request." Any particular rationale for this formatting?

Additionally, I'm interested in understanding the colour theme across the tabs. Is it possible to customize the vibrant colours individually, or should the website follow a consistent theme?

**Comment by maddox05** [comment]
sure!
1: I can answer all of your questions with 1 answer.  duckmath.org is meant for kids at school. Schools have tools the bl0ck key words from sites, such as titles and pages. I changed the titles to every page on the site and lost around 2k users just that day. Reverting it back seemed to fix it but the damage was done. I don't want any keywords in the site that would wind up getting it so my users cant use the site.
Color Theming: I am no artist and just liked the red. I would like for the site to follow a theme and I think it does that kinda well. If you want to change any of it, or have any other issues. Let me know! 
Thanks for asking these qs.
