### ISSUE TITLE
AVIF file doesn't work on all browsers

### ISSUE THREAD

**Issue by LightAndy1** [duckmath/duckmath.github.io#37]
As I use Microsoft Edge, I'm encountering visibility issues with some game icons because of the file format `.avif`; it seems to only work with `.webp`. I aim to address this issue tomorrow (November 14) after 2:00 PM. The solution involves replacing all `.avif` files with `.webp` to ensure seamless display of game icons.

**Comment by maddox05** [comment]
hi, can you show an example of this? Thanks Andy<3

**Comment by LightAndy1** [comment]
> hi, can you show an example of this? Thanks Andy<3

Yep, here is an example of the problem: ![Screenshot_20231113_112228_Edge.jpg](https://github.com/duckmath/duckmath.github.io/assets/50150516/33e78f18-eae6-4a53-b1e5-7e151b050e6a)

Although this is on the mobile version of Edge, it appears the same on the desktop version (without an icon).

**Comment by LightAndy1** [comment]
PR #38 resolves this issue. The icons should now load in all browsers (the most recent version is required).
