### ISSUE TITLE
css on streaks page is god awful

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#42]
need a css demon to help make streak.html look good and not like it was made by a 2-year-old on a piece of paper.

**Comment by LightAndy1** [comment]
Well, `streak.html` shows up to be kind of empty. Is there something I need to log in to see, or should the website be modified? :)
![streak.html page on duckmath.org](https://github.com/duckmath/duckmath.github.io/assets/50150516/a34e60fd-e931-4552-b472-d7db9c85a2e8)

**Comment by maddox05** [comment]
It's on a branch sorry, let me merge to main I'll lyk

**Comment by maddox05** [comment]
Give me a few hours and I'll merge it. Prob 3-4 hrs

**Comment by maddox05** [comment]
site should now be updated make sure to pull new changes!

**Comment by maddox05** [comment]
id like the stats at the bottom always and maybe a cool background for it.

**Comment by LightAndy1** [comment]
https://github.com/duckmath/duckmath.github.io/pull/44#issuecomment-1826298468
