### ISSUE TITLE
instead of adding new html pages, just show up the iframe on the same html page

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#5]
As the site has gotten bigger, it has been harder and harder to add HTML pages, copy everything from the old page, and only change certain things like titles and links. This would be a big redesign of the site.

**Comment by CarbonNeuron** [comment]
I think you'd need a type of web-framework for this? 
You could re-write your app in [Next.js](https://nextjs.org/) since you're already using Vercel to host your existing app.
That would allow you to use templating and whatnot to load different Iframe depending on which site was requested.

**Comment by CarbonNeuron** [comment]
I'd be interested in working on that with you if you are interested. I have developed quite a few nextjs applications.

**Comment by maddox05** [comment]
you can go ahead and try it, it will be a big task and will change the site dramatically. Id rather use js templates and just stick with vanilla js html css.
