### ISSUE TITLE
Instead of multiple pages we could add queries and parameters

### ISSUE THREAD

**Issue by LightAndy1** [duckmath/duckmath.github.io#59]
To not make a lot of pages for nothing, we can add a single page that acts as a template and in the link we can add something like:

```
...?g=cookie+clicker
```

Example:

```
https://duckmath.org/g4m3.html?g=cookie+clicker
```

This can help improving performance and it's pretty easy to do in JS, just get the parameter's name (from the URL) and then add the game's name and the game itself.

**Comment by maddox05** [comment]
Hi! That's a good idea and I should have added that a while ago. Sometime in the summer I'm going to make a new site or recode this one and I'll fix it there. Search parameters is a really good idea.
