### ISSUE TITLE
Scroller animation of header bug

### ISSUE THREAD

**Issue by LightAndy1** [duckmath/duckmath.github.io#68]
So for bigger screens (smaller web page), the topnav/header when scrolling is a bit off, as seen in the pictures below:

### 2K resolution
![image](https://github.com/duckmath/duckmath.github.io/assets/50150516/5c1b47ac-b981-4ecc-ad2e-8edee92eaa72)

### Smallest web page scale
![image](https://github.com/duckmath/duckmath.github.io/assets/50150516/0626b9e1-1eda-4625-ad08-035e0a70c0fb)

> I hope you can see it. You can also test it in your own browser by using `CTRL + Scroll down`

**Comment by maddox05** [comment]
@LightAndy1 is it fixed now with pr #72 ?

**Comment by LightAndy1** [comment]
Nope. In that PR there's only the custom scrollbar and a border bottom right radius of 15px to the header.

**Comment by LightAndy1** [comment]
Fixed by PR #77.
