### ISSUE TITLE
Mention Contributors.md in CONTRIBUTING.md

### ISSUE THREAD

**Issue by LightAndy1** [duckmath/duckmath.github.io#70]
In the CONTRIBUTING.md file, within the contributing guidelines, there should be a note encouraging contributors to include their name and GitHub link after their contribution.

---

So the file [Contributors.md](https://github.com/duckmath/duckmath.github.io/blob/main/Contributors.md) should be mentioned in the [CONTRIBUTING.md](https://github.com/duckmath/duckmath.github.io/blob/main/CONTRIBUTING.md) file.

**Comment by maddox05** [comment]
im not exactly sure what you mean but im merge the pr

**Comment by LightAndy1** [comment]
Fixed by PR #76.
