### ISSUE TITLE
Games aren't working

### ISSUE THREAD

**Issue by LightAndy1** [duckmath/duckmath.github.io#81]
I tried playing [Super Star Car](https://duckmath.org/g4m3s/Super-Star-Car.html), but I think this game is blocked from the providers (from Poki themselves) and can't be used as an embed/iframe.

![image](https://github.com/duckmath/duckmath.github.io/assets/50150516/3d3cbc90-a936-4f47-b6b1-5b569cd5fc60)

**Comment by LightAndy1** [comment]
Same for https://duckmath.org/g4m3s/rally-point.html

**Comment by maddox05** [comment]
fixed with commit
