### ISSUE TITLE
Create issue template for not working games and game suggestions

### ISSUE THREAD

**Issue by LightAndy1** [duckmath/duckmath.github.io#82]
I saw on some other GitHub projects there are some templates for issues and you just need to fill in the information as there are basically some prompts. I hope you understand what I'm trying to say (my brain is on low battery right now), I'll even attach a link to the documentation from GitHub related to the issue templates.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by maddox05** [comment]
done
