### ISSUE TITLE
topnav mobile issue fix does not work.

### ISSUE THREAD

**Issue by maddox05** [duckmath/duckmath.github.io#9]
top nav turns into popout, but when clicked does nothing. Needs to be fixed.

**Comment by Chayandev** [comment]
@maddox05  can u give one SS of the issue , I would like to work on it.

**Comment by maddox05** [comment]
sure! its supposed to show the topbar when the three lines are clicked but it does not. Someone else worked on it and they didn't do it right.
<img width="499" alt="Screenshot 2023-10-08 at 12 25 59 PM" src="https://github.com/duckmath/duckmath.github.io/assets/95244098/4259e217-01d8-4990-a215-313e213e7eaf">
<img width="494" alt="Screenshot 2023-10-08 at 12 26 06 PM" src="https://github.com/duckmath/duckmath.github.io/assets/95244098/c46b07bb-7ed7-48ac-9ce7-1f4780a77dfe">
